# Generated by Django 3.0.7 on 2020-11-12 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0036_order_orderproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'Элемент заказа', 'verbose_name_plural': 'Элементы заказа'},
        ),
    ]
