# Generated by Django 3.0.7 on 2020-12-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_auto_20201126_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='price',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Стоимость продукта'),
            preserve_default=False,
        ),
    ]
