# Generated by Django 3.0.7 on 2020-12-01 20:57

from django.db import migrations


def calculate_order_product_price(apps, schema_editor):
    OrderProduct = apps.get_model('foodcartapp', 'OrderProduct')
    for product in OrderProduct.objects.filter(price=0):
        product.price = product.product.price * product.quantity
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_orderproduct_price'),
    ]

    operations = [
        migrations.RunPython(calculate_order_product_price)
    ]
