# Generated by Django 3.0.7 on 2020-12-01 20:57

from django.db import migrations


def calculate_order_product_price(apps, schema_editor):
    OrderProduct = apps.get_model('foodcartapp', 'OrderProduct')
    orders_products_without_price = OrderProduct.objects.filter(price=0)
    for product in orders_products_without_price.iterator():
        product.price = product.product.price
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_orderproduct_price'),
    ]

    operations = [
        migrations.RunPython(calculate_order_product_price)
    ]
