# Generated by Django 3.0.7 on 2020-12-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_auto_20201201_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Необработанный заказ'), ('COMPLETED', 'Обработанный заказ')], default='NEW', max_length=15),
        ),
    ]
