# Generated by Django 3.0.7 on 2020-12-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Необработанный'), ('COMPLETED', 'Обработанный')], default='NEW', max_length=15, verbose_name='Статус заказа'),
        ),
    ]
