# Generated by Django 3.0.7 on 2021-02-13 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20210114_2139'),
        ('foodcartapp', '0037_auto_20210125_1833'),
    ]

    operations = [
    ]
