# Generated by Django 3.0.7 on 2021-02-14 15:21

from django.db import migrations
from phonenumber_field.modelfields import PhoneNumberField


def normalization_phone(apps, schema_editor):
    Order = apps.get_model("foodcartapp", "Order")
    for order in Order.objects.all():
        order.phonenumber = PhoneNumberField().get_prep_value(order.phonenumber)
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_auto_20210214_1516'),
    ]

    operations = [
        migrations.RunPython(normalization_phone)
    ]
