# Generated by Django 3.0.7 on 2021-02-14 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_auto_20210214_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='price',
            field=models.PositiveSmallIntegerField(verbose_name='Цена на момент создания заказа'),
        ),
    ]
