# Generated by Django 3.0.7 on 2021-02-17 18:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='request_to_geocoder_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Зарегистрирован в'),
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(db_index=True, max_length=500, verbose_name='Адрес'),
        ),
    ]
