# Generated by Django 3.0.13 on 2021-02-24 14:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_auto_20210221_0037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'элемент заказа', 'verbose_name_plural': 'элементы заказа'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'место', 'verbose_name_plural': 'места'},
        ),
        migrations.AlterField(
            model_name='place',
            name='request_to_geocoder_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Координаты получены'),
        ),
    ]
